# Generated by Django 5.2.5 on 2025-10-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
